import { Pool } from 'pg';
import { writeFile } from 'node:fs/promises';

// Syncs product_translations rows for ru/de/fr/es/it/ja/ar from local dev DB
// to prod (Webvisor 01.09.2026, задача 2 — заполнение отсутствующих
// переводов описаний байков). Upsert by (product slug, language_code), not
// (product_id, language_code) — ids are generated independently on each side
// and never line up (CLAUDE.md §6, "апсерт по бизнес-ключу — slug, не id").
// EN rows untouched (source of truth, not generated by this batch).

const pool = new Pool({ connectionString: 'postgres://localhost:5432/mdb_platform' });
const LANGS = ['ru', 'de', 'fr', 'es', 'it', 'ja', 'ar'];

function esc(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  const { rows } = await pool.query(
    `SELECT p.slug AS product_slug, t.language_code, t.title, t.description
     FROM product_translations t
     JOIN products p ON p.id = t.product_id
     WHERE t.language_code = ANY($1)
     ORDER BY p.slug, t.language_code`,
    [LANGS]
  );

  const out = [];
  out.push('-- product_translations_sync.sql — regenerated ' + new Date().toISOString().slice(0, 10));
  out.push('-- Syncs product_translations for ru/de/fr/es/it/ja/ar (title + description) from local');
  out.push('-- dev DB to prod. Idempotent (INSERT ... ON CONFLICT DO UPDATE), safe to re-run.');
  out.push('-- Upsert key: (products.slug, language_code) — NOT product_id (dev/prod ids differ).');
  out.push('-- EN rows are the source of truth and are not part of this sync.');
  out.push('BEGIN;');
  out.push('');
  out.push(`-- product_translations: ${rows.length} rows (${rows.length / LANGS.length} products x ${LANGS.length} languages)`);
  for (const r of rows) {
    out.push(
      `INSERT INTO product_translations (product_id, language_code, title, description)\n` +
      `  SELECT p.id, ${esc(r.language_code)}, ${esc(r.title)}, ${esc(r.description)}\n` +
      `  FROM products p WHERE p.slug = ${esc(r.product_slug)}\n` +
      `  ON CONFLICT (product_id, language_code) DO UPDATE SET\n` +
      `    title = EXCLUDED.title, description = EXCLUDED.description;`
    );
  }
  out.push('');
  out.push('COMMIT;');

  const sql = out.join('\n') + '\n';
  await writeFile(new URL('../../product_translations_sync.sql', import.meta.url), sql);
  console.log(`Wrote product_translations_sync.sql (${rows.length} rows).`);
  await pool.end();
}

main().catch((err) => { console.error(err); process.exit(1); });
