-- =====================================================================
-- MDB PLATFORM — DATABASE SCHEMA  (Opus build)
-- 10_equipment_mounting.sql
-- content merged into 009_fleet_amendments.sql, no-op to avoid duplicate enum/insert
-- =====================================================================

-- ALTER TYPE equipment_unit_status ADD VALUE 'installed';
--
-- INSERT INTO equipment_types (code, name, tracks_units, charge_basis, rental_price_idr, deposit_deduction_idr, deduction_note) VALUES
--     ('bracket_nmax', 'Bracket Nmax', TRUE, 'per_rental', 0, NULL, NULL),
--     ('bracket_adv160', 'Bracket ADV160', TRUE, 'per_rental', 0, NULL, NULL),
--     ('bracket_xmax', 'Bracket Xmax', TRUE, 'per_rental', 0, NULL, NULL),
--     ('bracket_mt25', 'Bracket MT25', TRUE, 'per_rental', 0, NULL, NULL),
--     ('bracket_xsr', 'Bracket XSR', TRUE, 'per_rental', 0, NULL, NULL),
--     ('bracket_pcx160', 'Bracket PCX160', TRUE, 'per_rental', 0, NULL, NULL),
--     ('baseplate', 'Baseplate', TRUE, 'per_rental', 0, NULL, NULL),
--     ('backrest', 'Backrest', TRUE, 'per_rental', 0, NULL, NULL);
