// Серверный словарь уведомлений менеджеру. Уведомление собирается ЦЕЛИКОМ на
// языке заявки (booking.locale) — без fallback на язык менеджера, без дублей.
// Названия оборудования приходят уже локализованными (equipment_type_translations).
// Переведён на все 9 языков сайта (2026-09-07) — раньше только en/ru, остальные
// молча падали на en через notifyDict() ?? NOTIFY.en ниже, ДО этой правки ещё и
// через SUPPORTED_LOCALES в booking.js (см. там), которая обрезала locale до
// en/ru раньше, чем он вообще доходил до notifyDict().
export const NOTIFY = {
  en: {
    lang_name: 'English',
    new_booking: 'New booking',
    lang_label: 'Language',
    days: 'days',
    mo: 'mo',
    calc: 'Breakdown',
    rental: 'Rental',
    delivery: 'Delivery',
    free: 'free',
    theft: 'Insurance: theft',
    bali_only: 'Bali only',
    damage: 'Insurance: damage',
    coverage: 'cover',
    exp: { experienced: 'experienced', inexperienced: 'inexperienced' },
    no_equipment: 'Equipment: —',
    to_pay: 'To pay',
    deposit: 'Deposit (refundable)',
    location_map: 'Location on map',
    location: 'Location',
    comment: 'Comment',
    payment: 'Payment',
    payment_cash: 'Cash',
    payment_bank_transfer: 'Bank transfer',
    payment_other: 'Other',
  },
  ru: {
    lang_name: 'Русский',
    new_booking: 'Новая заявка',
    lang_label: 'Язык',
    days: 'дн.',
    mo: 'мес.',
    calc: 'Расчёт',
    rental: 'Аренда',
    delivery: 'Доставка',
    free: 'бесплатно',
    theft: 'Страховка: угон',
    bali_only: 'только Бали',
    damage: 'Страховка: повреждения',
    coverage: 'покрытие',
    exp: { experienced: 'опытный', inexperienced: 'неопытный' },
    no_equipment: 'Оборудование: —',
    to_pay: 'К оплате',
    deposit: 'Депозит (возврат)',
    location_map: 'Локация на карте',
    location: 'Локация',
    comment: 'Комментарий',
    payment: 'Оплата',
    payment_cash: 'Наличные',
    payment_bank_transfer: 'Банковский перевод',
    payment_other: 'Другое',
  },
  de: {
    lang_name: 'Deutsch',
    new_booking: 'Neue Buchung',
    lang_label: 'Sprache',
    days: 'Tage',
    mo: 'Mon.',
    calc: 'Aufschlüsselung',
    rental: 'Miete',
    delivery: 'Lieferung',
    free: 'kostenlos',
    theft: 'Versicherung: Diebstahl',
    bali_only: 'nur Bali',
    damage: 'Versicherung: Schaden',
    coverage: 'Deckung',
    exp: { experienced: 'erfahren', inexperienced: 'unerfahren' },
    no_equipment: 'Ausrüstung: —',
    to_pay: 'Zu zahlen',
    deposit: 'Kaution (rückerstattbar)',
    location_map: 'Standort auf der Karte',
    location: 'Standort',
    comment: 'Kommentar',
    payment: 'Zahlung',
    payment_cash: 'Bar',
    payment_bank_transfer: 'Überweisung',
    payment_other: 'Sonstiges',
  },
  fr: {
    lang_name: 'Français',
    new_booking: 'Nouvelle réservation',
    lang_label: 'Langue',
    days: 'jours',
    mo: 'mois',
    calc: 'Détail',
    rental: 'Location',
    delivery: 'Livraison',
    free: 'gratuit',
    theft: 'Assurance : vol',
    bali_only: 'Bali uniquement',
    damage: 'Assurance : dommages',
    coverage: 'couverture',
    exp: { experienced: 'expérimenté', inexperienced: 'inexpérimenté' },
    no_equipment: 'Équipement : —',
    to_pay: 'À payer',
    deposit: 'Caution (remboursable)',
    location_map: 'Localisation sur la carte',
    location: 'Localisation',
    comment: 'Commentaire',
    payment: 'Paiement',
    payment_cash: 'Espèces',
    payment_bank_transfer: 'Virement bancaire',
    payment_other: 'Autre',
  },
  es: {
    lang_name: 'Español',
    new_booking: 'Nueva reserva',
    lang_label: 'Idioma',
    days: 'días',
    mo: 'mes(es)',
    calc: 'Desglose',
    rental: 'Alquiler',
    delivery: 'Entrega',
    free: 'gratis',
    theft: 'Seguro: robo',
    bali_only: 'solo Bali',
    damage: 'Seguro: daños',
    coverage: 'cobertura',
    exp: { experienced: 'con experiencia', inexperienced: 'sin experiencia' },
    no_equipment: 'Equipo: —',
    to_pay: 'A pagar',
    deposit: 'Depósito (reembolsable)',
    location_map: 'Ubicación en el mapa',
    location: 'Ubicación',
    comment: 'Comentario',
    payment: 'Pago',
    payment_cash: 'Efectivo',
    payment_bank_transfer: 'Transferencia bancaria',
    payment_other: 'Otro',
  },
  it: {
    lang_name: 'Italiano',
    new_booking: 'Nuova prenotazione',
    lang_label: 'Lingua',
    days: 'giorni',
    mo: 'mese/i',
    calc: 'Dettaglio',
    rental: 'Noleggio',
    delivery: 'Consegna',
    free: 'gratis',
    theft: 'Assicurazione: furto',
    bali_only: 'solo Bali',
    damage: 'Assicurazione: danni',
    coverage: 'copertura',
    exp: { experienced: 'esperto', inexperienced: 'inesperto' },
    no_equipment: 'Attrezzatura: —',
    to_pay: 'Da pagare',
    deposit: 'Cauzione (rimborsabile)',
    location_map: 'Posizione sulla mappa',
    location: 'Posizione',
    comment: 'Commento',
    payment: 'Pagamento',
    payment_cash: 'Contanti',
    payment_bank_transfer: 'Bonifico bancario',
    payment_other: 'Altro',
  },
  ja: {
    lang_name: '日本語',
    new_booking: '新規予約',
    lang_label: '言語',
    days: '日',
    mo: 'ヶ月',
    calc: '内訳',
    rental: 'レンタル料',
    delivery: '配送料',
    free: '無料',
    theft: '保険：盗難',
    bali_only: 'バリ島限定',
    damage: '保険：破損',
    coverage: '補償',
    exp: { experienced: '経験あり', inexperienced: '経験なし' },
    no_equipment: '装備：なし',
    to_pay: 'お支払い金額',
    deposit: 'デポジット（返金可）',
    location_map: '地図上の位置',
    location: '場所',
    comment: 'コメント',
    payment: '支払い方法',
    payment_cash: '現金',
    payment_bank_transfer: '銀行振込',
    payment_other: 'その他',
  },
  ar: {
    lang_name: 'العربية',
    new_booking: 'حجز جديد',
    lang_label: 'اللغة',
    days: 'أيام',
    mo: 'شهر',
    calc: 'التفاصيل',
    rental: 'الإيجار',
    delivery: 'التوصيل',
    free: 'مجاني',
    theft: 'التأمين: السرقة',
    bali_only: 'بالي فقط',
    damage: 'التأمين: الأضرار',
    coverage: 'التغطية',
    exp: { experienced: 'ذو خبرة', inexperienced: 'غير ذي خبرة' },
    no_equipment: 'المعدات: —',
    to_pay: 'المبلغ المستحق',
    deposit: 'التأمين القابل للاسترداد',
    location_map: 'الموقع على الخريطة',
    location: 'الموقع',
    comment: 'ملاحظة',
    payment: 'الدفع',
    payment_cash: 'نقدًا',
    payment_bank_transfer: 'تحويل بنكي',
    payment_other: 'أخرى',
  },
  ko: {
    lang_name: '한국어',
    new_booking: '신규 예약',
    lang_label: '언어',
    days: '일',
    mo: '개월',
    calc: '세부 내역',
    rental: '대여료',
    delivery: '배송비',
    free: '무료',
    theft: '보험: 도난',
    bali_only: '발리 한정',
    damage: '보험: 손상',
    coverage: '보장 범위',
    exp: { experienced: '경력자', inexperienced: '초보자' },
    no_equipment: '장비: —',
    to_pay: '결제 금액',
    deposit: '보증금 (환급 가능)',
    location_map: '지도상 위치',
    location: '위치',
    comment: '메모',
    payment: '결제 방법',
    payment_cash: '현금',
    payment_bank_transfer: '계좌 이체',
    payment_other: '기타',
  },
  hi: {
    lang_name: 'हिन्दी',
    new_booking: 'नई बुकिंग',
    lang_label: 'भाषा',
    days: 'दिन',
    mo: 'माह',
    calc: 'विवरण',
    rental: 'किराया',
    delivery: 'डिलीवरी',
    free: 'मुफ़्त',
    theft: 'इंश्योरेंस: चोरी',
    bali_only: 'सिर्फ़ बाली',
    damage: 'इंश्योरेंस: नुकसान',
    coverage: 'कवरेज',
    exp: { experienced: 'अनुभवी', inexperienced: 'अनुभवहीन' },
    no_equipment: 'इक्विपमेंट: —',
    to_pay: 'भुगतान राशि',
    deposit: 'डिपॉज़िट (रिफ़ंडेबल)',
    location_map: 'मैप पर लोकेशन',
    location: 'लोकेशन',
    comment: 'टिप्पणी',
    payment: 'भुगतान',
    payment_cash: 'नकद',
    payment_bank_transfer: 'बैंक ट्रांसफ़र',
    payment_other: 'अन्य',
  },
  'zh-Hans': {
    lang_name: '简体中文',
    new_booking: '新预订',
    lang_label: '语言',
    days: '天',
    mo: '个月',
    calc: '费用明细',
    rental: '租金',
    delivery: '送车费',
    free: '免费',
    theft: '保险：盗抢',
    bali_only: '仅限巴厘岛',
    damage: '保险：损坏',
    coverage: '保障范围',
    exp: { experienced: '有经验', inexperienced: '无经验' },
    no_equipment: '装备：—',
    to_pay: '应付金额',
    deposit: '押金（可退）',
    location_map: '地图位置',
    location: '位置',
    comment: '备注',
    payment: '付款方式',
    payment_cash: '现金',
    payment_bank_transfer: '银行转账',
    payment_other: '其他',
  },
};

export function notifyDict(locale) {
  return NOTIFY[locale] ?? NOTIFY.en;
}
